/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.aws;

import com.amazonaws.auth.PropertiesCredentials;
import com.amazonaws.services.sns.AmazonSNS;
import com.amazonaws.services.sns.AmazonSNSClient;
import com.amazonaws.services.sns.model.PublishRequest;
import com.amazonaws.services.sns.model.PublishResult;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Andres
 */
public class Notificaciones extends javax.swing.JFrame {

    /**
     * Creates new form Notificaciones
     */
    public Notificaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmessage = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txttitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnenviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Notificaciones");

        txtmessage.setColumns(20);
        txtmessage.setRows(5);
        jScrollPane1.setViewportView(txtmessage);

        jLabel2.setText("Titulo");

        jLabel3.setText("Mensaje");

        btnenviar.setText("Enviar");
        btnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnenviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                                .addComponent(txttitle))
                            .addComponent(btnenviar))))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnenviar)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnenviarActionPerformed

        try {
            /*
            * TODO: Be sure to fill in your AWS access credentials in the
            * AwsCredentials.properties file before you try to run this sample.
            * http://aws.amazon.com/security-credentials
             */
            AmazonSNS sns = new AmazonSNSClient(new PropertiesCredentials(new File("AwsCredentials.properties")));

            sns.setEndpoint("https://sns.us-east-1.amazonaws.com");

            PublishRequest publishRequest = new PublishRequest();
            publishRequest.setTopicArn("arn:aws:sns:us-east-1:951069153692:CoffeShop");

            String Title = txttitle.getText();
            String Message = txtmessage.getText();
            publishRequest.setMessage("{\n"
                    + "  \"default\": \"Ejemplo de mensaje alternativo\",\n"
                    + "  \"email\": \"Ejemplo de mensaje para puntos de enlace de correo electrónico\",\n"
                    + "  \"sqs\": \"Ejemplo de mensaje para puntos de enlace de Amazon SQS\",\n"
                    + "  \"lambda\": \"Ejemplo de mensaje para puntos de enlace de AWS Lambda\",\n"
                    + "  \"http\": \"Ejemplo de mensaje para puntos de enlace HTTP\",\n"
                    + "  \"https\": \"Ejemplo de mensaje para puntos de enlace HTTPS\",\n"
                    + "  \"sms\": \"Ejemplo de mensaje para puntos de enlace de SMS\",\n"
                    + "  \"firehose\": \"Mensaje de muestra para puntos de enlace de Amazon Kinesis Data Firehose\",\n"
                    + "  \"APNS\": \"{\\\"aps\\\":{\\\"alert\\\": \\\"Sample message for iOS endpoints\\\"} }\",\n"
                    + "  \"APNS_SANDBOX\": \"{\\\"aps\\\":{\\\"alert\\\":\\\"Sample message for iOS development endpoints\\\"}}\",\n"
                    + "  \"APNS_VOIP\": \"{\\\"aps\\\":{\\\"alert\\\":\\\"Sample message for Apple VoIP endpoints\\\"}}\",\n"
                    + "  \"APNS_VOIP_SANDBOX\": \"{\\\"aps\\\":{\\\"alert\\\": \\\"Sample message for Apple VoIP development endpoints\\\"} }\",\n"
                    + "  \"MACOS\": \"{\\\"aps\\\":{\\\"alert\\\":\\\"Sample message for MacOS endpoints\\\"}}\",\n"
                    + "  \"MACOS_SANDBOX\": \"{\\\"aps\\\":{\\\"alert\\\": \\\"Sample message for MacOS development endpoints\\\"} }\",\n"
                    + "  \"GCM\": \"{\\\"notification\\\": { \\\"body\\\": \\\"" + Message + "\\\", \\\"title\\\":\\\"" + Title + "\\\",\\\"sound\\\":\\\"default\\\" }, \\\"priority\\\": \\\"high\\\" }\",\n"
                    + "  \"ADM\": \"{\\\"data\\\": { \\\"message\\\": \\\"Sample message for FireOS endpoints\\\" } }\",\n"
                    + "  \"BAIDU\": \"{\\\"title\\\":\\\"Sample message title\\\",\\\"description\\\":\\\"Sample message for Baidu endpoints\\\"}\",\n"
                    + "  \"MPNS\": \"<?xml version=\\\"1.0\\\" encoding=\\\"utf-8\\\"?><wp:Notification xmlns:wp=\\\"WPNotification\\\"><wp:Tile><wp:Count>INGRESAR RECUENTO</wp:Count><wp:Title>Ejemplo de mensaje para puntos de enlace de Windows Phone 7 y versiones posteriores</wp:Title></wp:Tile></wp:Notification>\",\n"
                    + "  \"WNS\": \"<badge version=\\\"1\\\" value=\\\"42\\\"/>\"\n"
                    + "}");
            publishRequest.setMessageStructure("json");
            System.out.println("Publist request:" + publishRequest.toString());

            PublishResult publishResult = sns.publish(publishRequest);
            System.out.println(publishResult.toString());
            System.out.println(publishResult.getSdkResponseMetadata().toString());
            System.out.println("===========================================\n");
            System.out.println("Getting Started with Amazon SNS");
            System.out.println("===========================================\n");
        } catch (IOException ex) {
            Logger.getLogger(Notificaciones.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(Notificaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnenviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnenviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtmessage;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables
}
